site_name: Minr Docs
site_url: https://x3a1n4.github.io/minr-docs
repo_url: https://github.com/x3a1n4/minr-docs
plugins:
  - tags
  - search
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    tag:
      default: material/tag
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  tags:
    Mapmaking: mapmaking
    Scripting: scripting
    Internal: internal
not_in_nav: |
  /tags.md
hooks:
  - src/hooks/shortcodes.py
extra_css:
  - stylesheets/badges.css
markdown_extensions:
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg